apiVersion: v1
kind: Namespace
metadata:
  name: asr-service
---
# --- NATS JetStream ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: asr-service
data:
  nats.conf: |
    # 核心配置：允许 10MB 的大包 (音频数据)
    max_payload: 10MB
    
    # 开启 JetStream 并指定存储路径
    jetstream {
        store_dir: "/data"
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: asr-service
spec:
  serviceName: nats
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      nodeSelector: 
        device: usbssd    
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: nats-storage
          mountPath: /data    
      containers:
      - name: nats
        image: nats:2.10-alpine
        args: ["-c", "/etc/nats-config/nats.conf"] 
        ports:
        - containerPort: 4222
        volumeMounts:
        - name: nats-storage
          mountPath: /data
        - name: config-volume
          mountPath: /etc/nats-config
      volumes:
      - name: config-volume
        configMap:
          name: nats-config        
  volumeClaimTemplates:
  - metadata:
      name: nats-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources: { requests: { storage: 5Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: asr-service
spec:
  type: NodePort
  ports:
  - port: 4222
    nodePort: 30742
  selector:
    app: nats
---
# --- MongoDB ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: asr-service
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector: 
        device: usbssd
      containers:
      - name: mongo
        image: mongo:4.4.18
        # 限制内存，防止吃光树莓派内存
        args: ["--wiredTigerCacheSizeGB", "0.5"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        hostPath:
          path: /data/mongo_data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: asr-service
spec:
  type: NodePort
  ports:
  - port: 27017
    nodePort: 30327
  selector:
    app: mongo